/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 office2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/office2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Shelf_Clutter" position={[3.86, 1.656, 1.182]} rotation={[0, Math.PI / 2, 0]} scale={100}>
        <mesh name="Shelf_Clutter_1" geometry={nodes.Shelf_Clutter_1.geometry} material={materials.mat22} />
        <mesh name="Shelf_Clutter_2" geometry={nodes.Shelf_Clutter_2.geometry} material={materials.mat17} />
        <mesh name="Shelf_Clutter_3" geometry={nodes.Shelf_Clutter_3.geometry} material={materials.mat15} />
        <mesh name="Shelf_Clutter_4" geometry={nodes.Shelf_Clutter_4.geometry} material={materials.mat1} />
        <mesh name="Shelf_Clutter_5" geometry={nodes.Shelf_Clutter_5.geometry} material={materials.mat21} />
        <mesh name="Shelf_Clutter_6" geometry={nodes.Shelf_Clutter_6.geometry} material={materials.mat11} />
        <mesh name="Shelf_Clutter_7" geometry={nodes.Shelf_Clutter_7.geometry} material={materials.mat20} />
        <mesh name="Shelf_Clutter_8" geometry={nodes.Shelf_Clutter_8.geometry} material={materials.mat16} />
        <mesh name="Shelf_Clutter_9" geometry={nodes.Shelf_Clutter_9.geometry} material={materials.mat24} />
        <mesh name="Shelf_Clutter_10" geometry={nodes.Shelf_Clutter_10.geometry} material={materials.mat8} />
        <mesh name="Shelf_Clutter_11" geometry={nodes.Shelf_Clutter_11.geometry} material={materials.mat23} />
        <mesh name="Shelf_Clutter_12" geometry={nodes.Shelf_Clutter_12.geometry} material={materials.mat7} />
        <mesh name="Shelf_Clutter_13" geometry={nodes.Shelf_Clutter_13.geometry} material={materials.mat12} />
        <mesh name="Shelf_Clutter_14" geometry={nodes.Shelf_Clutter_14.geometry} material={materials.mat4} />
        <mesh name="Shelf_Clutter_15" geometry={nodes.Shelf_Clutter_15.geometry} material={materials.mat10} />
      </group>
      <group name="Window" position={[-0.002, 0.959, -3.985]}>
        <mesh name="Window_1" geometry={nodes.Window_1.geometry} material={materials.PVC} />
        <mesh name="Window_2" geometry={nodes.Window_2.geometry} material={materials.Plastic} />
        <mesh name="Window_3" geometry={nodes.Window_3.geometry} material={materials.Marble} />
      </group>
      <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} position={[0.244, 0, 0.254]} rotation={[0, -0.122, 0]} scale={0.901} />
      <mesh name="Keyboard1" geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} />
      <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={materials.lambert3SG} />
      <group name="piano" position={[0, 0, 0.567]}>
        <mesh name="piano_1" geometry={nodes.piano_1.geometry} material={materials['_crayfishdiffuse.001']} />
        <mesh name="piano_2" geometry={nodes.piano_2.geometry} material={materials['02___Default.001']} />
      </group>
      <group name="Desk" position={[0, 0, 0.577]} rotation={[Math.PI, 0, Math.PI]} scale={0.901}>
        <mesh name="Desk_1" geometry={nodes.Desk_1.geometry} material={materials.DarkWood} />
        <mesh name="Desk_2" geometry={nodes.Desk_2.geometry} material={materials.Wood} />
      </group>
      <mesh name="RubberFigPottedPlant_mesh" geometry={nodes.RubberFigPottedPlant_mesh.geometry} material={materials.RubberFigPottedPlant_mat} />
      <group name="SM_Desk_armchair" position={[0, 0, 0.079]}>
        <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['Cadeira escritorio Plastic_Rough']} />
        <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials['Cadeira escritorio Plastic.Rough_Light']} />
        <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials[' Cadeira escritorio Plastic']} />
        <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials[' Cadeira escritorio Metal']} />
        <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials[' Cadeira escritorio Metal_Black']} />
        <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials[' Cadeira escritorio Plastic_Rough.001']} />
        <mesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={materials[' Cadeira escritorio Material']} />
      </group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['plank-floor']} />
      <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.walls} />
      <mesh name="System_unit_1" geometry={nodes.System_unit_1.geometry} material={materials.lambert3SG} />
      <mesh name="System_unit_1_1" geometry={nodes.System_unit_1_1.geometry} material={materials.initialShadingGroup} />
      <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Metal} />
      <mesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={materials.Velvet} />
    </group>
  )
}

useGLTF.preload('/office2.glb')
