/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 portfolioroombaked5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/portfolioroombaked5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} position={[0.05, 0, 0.275]} rotation={[0, -0.122, 0]} scale={0.901} />
      <mesh name="Keyboard1" geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} position={[0, 0, 0.106]} scale={0.901} />
      <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={materials.lambert3SG} position={[0, 0, 0.072]} scale={0.901} />
      <mesh name="RubberFigPottedPlant_mesh" geometry={nodes.RubberFigPottedPlant_mesh.geometry} material={materials.RubberFigPottedPlant_mat} />
      <group name="System_unit" position={[0, 0, 0.012]} scale={0.901}>
        <mesh name="System_unit_1" geometry={nodes.System_unit_1.geometry} material={materials.lambert3SG} />
        <mesh name="System_unit_1_1" geometry={nodes.System_unit_1_1.geometry} material={materials.initialShadingGroup} />
      </group>
      <group name="SM_Desk_armchair" position={[0, 0, 0.079]}>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Cadeira escritorio Plastic_Rough']} />
        <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['Cadeira escritorio Plastic.Rough_Light']} />
        <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials[' Cadeira escritorio Plastic']} />
        <mesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials[' Cadeira escritorio Metal']} />
        <mesh name="Cube003_4" geometry={nodes.Cube003_4.geometry} material={materials[' Cadeira escritorio Metal_Black']} />
        <mesh name="Cube003_5" geometry={nodes.Cube003_5.geometry} material={materials[' Cadeira escritorio Plastic_Rough.001']} />
        <mesh name="Cube003_6" geometry={nodes.Cube003_6.geometry} material={materials[' Cadeira escritorio Material']} />
      </group>
      <group name="Window" position={[-0.002, 0.959, -3.985]}>
        <mesh name="Window_1" geometry={nodes.Window_1.geometry} material={materials.PVC} />
        <mesh name="Window_2" geometry={nodes.Window_2.geometry} material={materials.Plastic} />
        <mesh name="Window_3" geometry={nodes.Window_3.geometry} material={materials.Glass} />
        <mesh name="Window_4" geometry={nodes.Window_4.geometry} material={materials.Marble} />
      </group>
      <group name="Desk" position={[0, 0, 0.577]} rotation={[Math.PI, 0, Math.PI]} scale={0.901}>
        <mesh name="Desk_1" geometry={nodes.Desk_1.geometry} material={materials.DarkWood} />
        <mesh name="Desk_2" geometry={nodes.Desk_2.geometry} material={materials.Wood} />
      </group>
      <group name="air_conditioner,_heater" position={[2.164, 0.913, -1.521]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="网格5916" geometry={nodes.网格5916.geometry} material={materials['9_09___Default_']} />
        <mesh name="网格5916_1" geometry={nodes.网格5916_1.geometry} material={materials['18_12___Default_']} />
        <mesh name="网格5916_2" geometry={nodes.网格5916_2.geometry} material={materials.FABRIC_1_FRONT_3863} />
        <mesh name="网格5916_3" geometry={nodes.网格5916_3.geometry} material={materials['3_06___Defajrtrtult_']} />
        <mesh name="网格5916_4" geometry={nodes.网格5916_4.geometry} material={materials['3_24___Default_']} />
        <mesh name="网格5916_5" geometry={nodes.网格5916_5.geometry} material={materials['20 -jr5tt']} />
        <mesh name="网格5916_6" geometry={nodes.网格5916_6.geometry} material={materials['14_05___Default_']} />
        <mesh name="网格5916_7" geometry={nodes.网格5916_7.geometry} material={materials['17_12___Default_']} />
        <mesh name="网格5916_8" geometry={nodes.网格5916_8.geometry} material={materials['19_01 - Defaultrehj_']} />
        <mesh name="网格5916_9" geometry={nodes.网格5916_9.geometry} material={materials['22_14 - Default_']} />
        <mesh name="网格5916_10" geometry={nodes.网格5916_10.geometry} material={materials['21_14 - Default_']} />
        <mesh name="网格5916_11" geometry={nodes.网格5916_11.geometry} material={materials['23455_06___Default_']} />
      </group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['plank-floor']} />
      <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.walls} />
      <mesh name="piano_1" geometry={nodes.piano_1.geometry} material={materials['_crayfishdiffuse.001']} />
      <mesh name="piano_2" geometry={nodes.piano_2.geometry} material={materials['02___Default.001']} />
      <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Metal} />
      <mesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={materials.Velvet} />
    </group>
  )
}

useGLTF.preload('/portfolioroombaked5.glb')
