/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 portfolioroombaked2.glb -k 
*/

import React, { useEffect } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from 'framer-motion';
import { useFrame } from '@react-three/fiber';

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF('models/office/office22.glb');
  const texture = useTexture("textures/bake22.png");
  texture.flipY = false;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });
  //make textures transparent when section is changed
  const textureOpicity = useMotionValue(0);
  
  useEffect(()=>{
    animate(textureOpicity, section === 0 ? 1 : 0, {
      duration: 0.8,
    });

  },[section]);

  useFrame(()=>{
    textureMaterial.opacity = textureOpicity.get();
  });

  return (
    <group {...props} dispose={null}>
      <group name="Window" position={[-0.002, 0.959, -3.985]}>
        <mesh name="Window_1" geometry={nodes.Window_1.geometry} material={textureMaterial}  />
        <mesh name="Window_2" geometry={nodes.Window_2.geometry} material={textureMaterial}  />
        <mesh name="Window_3" geometry={nodes.Window_3.geometry} material={textureMaterial}  />
      </group>
      <motion.group name='computer' animate={{
        scale: section === 0 ? 1 : 0,
      }}>
        <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={textureMaterial}  position={[0.244, 0, 0.254]} rotation={[0, -0.122, 0]} scale={0.901} />
        <mesh name="Keyboard1" geometry={nodes.Keyboard1.geometry} material={textureMaterial}  />
        <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={textureMaterial}  />
        <mesh name="System_unit_1" geometry={nodes.System_unit_1.geometry} material={textureMaterial}  />
        <mesh name="System_unit_1_1" geometry={nodes.System_unit_1_1.geometry} material={textureMaterial}  />

      </motion.group>
      
      <group name="piano" position={[0, 0, 0.567]} >
        <mesh name="piano_1" geometry={nodes.piano_1.geometry} material={textureMaterial}  />
        <mesh name="piano_2" geometry={nodes.piano_2.geometry} material={textureMaterial}  />
      </group>
      <motion.group name="Desk" position={[0, 0, 0.577]} rotation={[Math.PI, 0, Math.PI]} animate={{
        scale: section === 0 ? 0.901 : 0,
      }} >
        <mesh name="Desk_1" geometry={nodes.Desk_1.geometry} material={textureMaterial}  />
        <mesh name="Desk_2" geometry={nodes.Desk_2.geometry} material={textureMaterial}  />
      </motion.group>
      <mesh name="RubberFigPottedPlant_mesh" geometry={nodes.RubberFigPottedPlant_mesh.geometry} material={textureMaterial}  />
      <motion.group name="SM_Desk_armchair" position={[0, 0, 0.079]} animate={{
        scale: section === 0 ? 0.901 : 0,
        
      }}>
        <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={textureMaterial}  />
        <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={textureMaterial}  />
        <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={textureMaterial}  />
        <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={textureMaterial}  />
        <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={textureMaterial}  />
        <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={textureMaterial}  />
        <mesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={textureMaterial}  />
      </motion.group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial}  />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial}  />
      <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={textureMaterial}  />
      
      <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={textureMaterial}  />
      <mesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_1" geometry={nodes.Shelf_Clutter_1.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_2" geometry={nodes.Shelf_Clutter_2.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_3" geometry={nodes.Shelf_Clutter_3.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_4" geometry={nodes.Shelf_Clutter_4.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_5" geometry={nodes.Shelf_Clutter_5.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_6" geometry={nodes.Shelf_Clutter_6.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_7" geometry={nodes.Shelf_Clutter_7.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_8" geometry={nodes.Shelf_Clutter_8.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_9" geometry={nodes.Shelf_Clutter_9.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_10" geometry={nodes.Shelf_Clutter_10.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_11" geometry={nodes.Shelf_Clutter_11.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_12" geometry={nodes.Shelf_Clutter_12.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_13" geometry={nodes.Shelf_Clutter_13.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_14" geometry={nodes.Shelf_Clutter_14.geometry} material={textureMaterial}  />
      <mesh name="Shelf_Clutter_15" geometry={nodes.Shelf_Clutter_15.geometry} material={textureMaterial}  />
    </group>
  )
}

useGLTF.preload('models/office/office22.glb');
useTexture.preload("textures/bake22.png");
